name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Rodar arquivo específico do Cypress
        run: npx cypress run --browser chrome --headless --spec "cypress/e2e/CamposPersonalizadoESMP.cy.js"

      - name: Upload de screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Upload de vídeos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: cypress/videos